export const WS_CONNECTION_START_FEED: 'WS_CONNECTION_START_FEED' = 'WS_CONNECTION_START_FEED';
export const WS_CONNECTION_START_PROFILE: 'WS_CONNECTION_START_PROFILE' = 'WS_CONNECTION_START_PROFILE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS'; 
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_DISCONNECT: 'WS_DISCONNECT' = 'WS_DISCONNECT';
